# Generated by Django 3.2.19 on 2023-06-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230602_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_updated_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
